/**
 * What changed, written for the person using Ember.
 *
 * Not read from CHANGELOG.md on purpose. That file is generated by release-please from commit
 * subjects, so it carries entries like "release 1.0.0" with a commit hash next to them: true,
 * and useless to anyone who is not reading the repository. These lines are written by hand when
 * a release is cut, which is the only moment anyone knows what the release actually means.
 *
 * Newest first. When you cut a release, add an entry at the top with the version string exactly
 * as `getVersion()` reports it, and three lines at most: About shows the entry for the running
 * version and NOTHING when there is no match, so a stale list can never describe a build it was
 * not written for.
 *
 * That cuts both ways, and it caught one out already: this list carried the settings release
 * under 1.1.0-rc.2, a version that shipped months of work earlier and never had any of it, and
 * the release that did have it would have shown an empty About. The version here is the one
 * release-please is about to publish, not the one you happen to be running while you write it.
 */
export interface Release {
  version: string;
  lines: string[];
}

export const RELEASES: Release[] = [
  {
    version: "1.2.0-rc.2",
    lines: [
      "Every settings tab fits the window now, and the window remembers where you left it.",
      "A Reply mode that answers the message you selected, on a shortcut of its own.",
      "Three marks for the ember beside your cursor, in three sizes.",
    ],
  },
  {
    version: "1.1.0-rc.1",
    lines: [
      "The ember follows the cursor without drifting, and project pills sit where you expect.",
      "Protected text and accented characters survive a refine untouched.",
      "Credentials are bound to the endpoint they were given for.",
    ],
  },
];

/** The entry for the build that is running, or null when this list has nothing to say about it. */
export function releaseFor(version: string | null): Release | null {
  if (!version) return null;
  return RELEASES.find(r => r.version === version) ?? null;
}
