/**
 * What changed, written for the person using Ember.
 *
 * Not read from CHANGELOG.md on purpose. That file is generated by release-please from commit
 * subjects, so it carries entries like "release 1.0.0" with a commit hash next to them: true,
 * and useless to anyone who is not reading the repository. These lines are written by hand when
 * a release is cut, which is the only moment anyone knows what the release actually means.
 *
 * Newest first, keyed by the RELEASE, not by the build: an entry for 1.2.0 covers 1.2.0-rc.3,
 * 1.2.0-rc.4 and 1.2.0 itself, because candidates of a version are that version being tried.
 * Writing the full build string here meant a new entry with every candidate, and the two times
 * it was missed the About card went blank on the release that had the work in it.
 *
 * About shows the entry whose release matches and NOTHING when none does, so a stale list still
 * cannot describe a version it was not written for. Three lines at most, in plain words: this is
 * the only place the app tells someone what changed.
 */
export interface Release {
  version: string;
  lines: string[];
}

export const RELEASES: Release[] = [
  {
    version: "1.2.0",
    lines: [
      "Every settings tab fits the window now, and the window remembers where you left it.",
      "A Reply mode that answers the message you selected, on a shortcut of its own.",
      "Three marks for the ember beside your cursor, in three sizes.",
    ],
  },
  {
    version: "1.1.0",
    lines: [
      "The ember follows the cursor without drifting, and project pills sit where you expect.",
      "Protected text and accented characters survive a refine untouched.",
      "Credentials are bound to the endpoint they were given for.",
    ],
  },
];

/** The release a version belongs to: 1.2.0-rc.4 and 1.2.0 are the same release being tried. */
function releaseOf(version: string) {
  return version.split("-")[0];
}

/** The entry for the build that is running, or null when this list has nothing to say about it. */
export function releaseFor(version: string | null): Release | null {
  if (!version) return null;
  const release = releaseOf(version);
  return RELEASES.find(r => releaseOf(r.version) === release) ?? null;
}
